doctrine:
    dbal:
        driver:   "pdo_mysql"
        host:     "127.0.0.1"
        port:     "3306"
        dbname:   "meettheteam"
        user:     "root"
        password: "password"
        server_version: '5.7.22'
        charset: UTF8
        default_table_options:
            charset: UTF8
            collate: utf8_unicode_ci

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
