<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMD3PSN\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMD3PSN/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTMD3PSN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerTMD3PSN\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerTMD3PSN\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'TMD3PSN',
    'container.build_id' => '2c3575a3',
    'container.build_time' => 1598329403,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMD3PSN');
