<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'colleague_index' => [[], ['_controller' => 'App\\Controller\\ColleagueController::index'], [], [['text', '/colleague/']], [], []],
    'colleague_new' => [[], ['_controller' => 'App\\Controller\\ColleagueController::new'], [], [['text', '/colleague/new']], [], []],
    'colleague_show' => [['id'], ['_controller' => 'App\\Controller\\ColleagueController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/colleague']], [], []],
    'colleague_edit' => [['id'], ['_controller' => 'App\\Controller\\ColleagueController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/colleague']], [], []],
    'colleague_delete' => [['id'], ['_controller' => 'App\\Controller\\ColleagueController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/colleague']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/']], [], []],
    'confirmOtp' => [[], ['_controller' => 'App\\Controller\\SecurityController::confirmOtp'], [], [['text', '/confirmOtp']], [], []],
    'logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
