<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYDNX83e\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYDNX83e/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYDNX83e.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYDNX83e\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYDNX83e\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YDNX83e',
    'container.build_id' => '9fe17611',
    'container.build_time' => 1598329327,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYDNX83e');
